# Generated by Django 2.2.2 on 2019-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('editorial', models.CharField(max_length=80)),
                ('numPag', models.SmallIntegerField()),
                ('autores', models.SmallIntegerField()),
            ],
        ),
    ]
