# Generated by Django 2.2.2 on 2019-06-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_prestamo_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='libros',
        ),
    ]
