# Generated by Django 2.2.2 on 2019-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libros',
            field=models.ManyToManyField(to='catalogo.Libro'),
        ),
    ]
